/* Generated by Yosys 0.9+4052 (git sha1 UNKNOWN, gcc 8.3.1 -fPIC -Os) */

module user_analog_project_wrapper(vdda1, vdda2, vssa1, vssa2, vccd1, vccd2, vssd1, vssd2, wb_clk_i, wb_rst_i, wbs_stb_i, wbs_cyc_i, wbs_we_i, wbs_sel_i, wbs_dat_i, wbs_adr_i, wbs_ack_o, wbs_dat_o, la_data_in, la_data_out, la_oenb, io_in, io_in_3v3, io_out, io_oeb, gpio_analog, gpio_noesd, io_analog, io_clamp_high, io_clamp_low, user_clock2, user_irq);
  wire \fastio_in[0] ;
  wire \fastio_in[10] ;
  wire \fastio_in[11] ;
  wire \fastio_in[12] ;
  wire \fastio_in[13] ;
  wire \fastio_in[14] ;
  wire \fastio_in[15] ;
  wire \fastio_in[16] ;
  wire \fastio_in[17] ;
  wire \fastio_in[18] ;
  wire \fastio_in[19] ;
  wire \fastio_in[1] ;
  wire \fastio_in[20] ;
  wire \fastio_in[21] ;
  wire \fastio_in[22] ;
  wire \fastio_in[23] ;
  wire \fastio_in[24] ;
  wire \fastio_in[25] ;
  wire \fastio_in[26] ;
  wire \fastio_in[27] ;
  wire \fastio_in[2] ;
  wire \fastio_in[3] ;
  wire \fastio_in[4] ;
  wire \fastio_in[5] ;
  wire \fastio_in[6] ;
  wire \fastio_in[7] ;
  wire \fastio_in[8] ;
  wire \fastio_in[9] ;
  wire \fastio_med_enable[0] ;
  wire \fastio_med_enable[10] ;
  wire \fastio_med_enable[11] ;
  wire \fastio_med_enable[12] ;
  wire \fastio_med_enable[13] ;
  wire \fastio_med_enable[14] ;
  wire \fastio_med_enable[15] ;
  wire \fastio_med_enable[16] ;
  wire \fastio_med_enable[17] ;
  wire \fastio_med_enable[18] ;
  wire \fastio_med_enable[19] ;
  wire \fastio_med_enable[1] ;
  wire \fastio_med_enable[20] ;
  wire \fastio_med_enable[21] ;
  wire \fastio_med_enable[22] ;
  wire \fastio_med_enable[23] ;
  wire \fastio_med_enable[24] ;
  wire \fastio_med_enable[25] ;
  wire \fastio_med_enable[26] ;
  wire \fastio_med_enable[27] ;
  wire \fastio_med_enable[2] ;
  wire \fastio_med_enable[3] ;
  wire \fastio_med_enable[4] ;
  wire \fastio_med_enable[5] ;
  wire \fastio_med_enable[6] ;
  wire \fastio_med_enable[7] ;
  wire \fastio_med_enable[8] ;
  wire \fastio_med_enable[9] ;
  wire \fastio_oe_l[0] ;
  wire \fastio_oe_l[10] ;
  wire \fastio_oe_l[11] ;
  wire \fastio_oe_l[12] ;
  wire \fastio_oe_l[13] ;
  wire \fastio_oe_l[14] ;
  wire \fastio_oe_l[15] ;
  wire \fastio_oe_l[16] ;
  wire \fastio_oe_l[17] ;
  wire \fastio_oe_l[18] ;
  wire \fastio_oe_l[19] ;
  wire \fastio_oe_l[1] ;
  wire \fastio_oe_l[20] ;
  wire \fastio_oe_l[21] ;
  wire \fastio_oe_l[22] ;
  wire \fastio_oe_l[23] ;
  wire \fastio_oe_l[24] ;
  wire \fastio_oe_l[25] ;
  wire \fastio_oe_l[26] ;
  wire \fastio_oe_l[27] ;
  wire \fastio_oe_l[2] ;
  wire \fastio_oe_l[3] ;
  wire \fastio_oe_l[4] ;
  wire \fastio_oe_l[5] ;
  wire \fastio_oe_l[6] ;
  wire \fastio_oe_l[7] ;
  wire \fastio_oe_l[8] ;
  wire \fastio_oe_l[9] ;
  wire \fastio_out_l[0] ;
  wire \fastio_out_l[10] ;
  wire \fastio_out_l[11] ;
  wire \fastio_out_l[12] ;
  wire \fastio_out_l[13] ;
  wire \fastio_out_l[14] ;
  wire \fastio_out_l[15] ;
  wire \fastio_out_l[16] ;
  wire \fastio_out_l[17] ;
  wire \fastio_out_l[18] ;
  wire \fastio_out_l[19] ;
  wire \fastio_out_l[1] ;
  wire \fastio_out_l[20] ;
  wire \fastio_out_l[21] ;
  wire \fastio_out_l[22] ;
  wire \fastio_out_l[23] ;
  wire \fastio_out_l[24] ;
  wire \fastio_out_l[25] ;
  wire \fastio_out_l[26] ;
  wire \fastio_out_l[27] ;
  wire \fastio_out_l[2] ;
  wire \fastio_out_l[3] ;
  wire \fastio_out_l[4] ;
  wire \fastio_out_l[5] ;
  wire \fastio_out_l[6] ;
  wire \fastio_out_l[7] ;
  wire \fastio_out_l[8] ;
  wire \fastio_out_l[9] ;
  wire \fastio_strong_enable[0] ;
  wire \fastio_strong_enable[10] ;
  wire \fastio_strong_enable[11] ;
  wire \fastio_strong_enable[12] ;
  wire \fastio_strong_enable[13] ;
  wire \fastio_strong_enable[14] ;
  wire \fastio_strong_enable[15] ;
  wire \fastio_strong_enable[16] ;
  wire \fastio_strong_enable[17] ;
  wire \fastio_strong_enable[18] ;
  wire \fastio_strong_enable[19] ;
  wire \fastio_strong_enable[1] ;
  wire \fastio_strong_enable[20] ;
  wire \fastio_strong_enable[21] ;
  wire \fastio_strong_enable[22] ;
  wire \fastio_strong_enable[23] ;
  wire \fastio_strong_enable[24] ;
  wire \fastio_strong_enable[25] ;
  wire \fastio_strong_enable[26] ;
  wire \fastio_strong_enable[27] ;
  wire \fastio_strong_enable[2] ;
  wire \fastio_strong_enable[3] ;
  wire \fastio_strong_enable[4] ;
  wire \fastio_strong_enable[5] ;
  wire \fastio_strong_enable[6] ;
  wire \fastio_strong_enable[7] ;
  wire \fastio_strong_enable[8] ;
  wire \fastio_strong_enable[9] ;
  inout [17:0] gpio_analog;
  inout [17:0] gpio_noesd;
  inout [10:0] io_analog;
  inout [2:0] io_clamp_high;
  inout [2:0] io_clamp_low;
  input [26:0] io_in;
  input [26:0] io_in_3v3;
  output [26:0] io_oeb;
  output [26:0] io_out;
  input [127:0] la_data_in;
  output [127:0] la_data_out;
  input [127:0] la_oenb;
  input user_clock2;
  output [2:0] user_irq;
  inout vccd1;
  inout vccd2;
  inout vdda1;
  inout vdda2;
  inout vssa1;
  inout vssa2;
  inout vssd1;
  inout vssd2;
  input wb_clk_i;
  input wb_rst_i;
  output wbs_ack_o;
  input [31:0] wbs_adr_i;
  input wbs_cyc_i;
  input [31:0] wbs_dat_i;
  output [31:0] wbs_dat_o;
  input [3:0] wbs_sel_i;
  input wbs_stb_i;
  input wbs_we_i;
  
  armleo_gpio fastio0 (
    .in(\fastio_in[0] ),
    .med_enable(\fastio_med_enable[0] ),
    .oe_l(\fastio_oe_l[0] ),
    .out_l(\fastio_out_l[0] ),
    .pad(gpio_noesd[0]),
    .strong_enable(\fastio_strong_enable[0] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio1 (
    .in(\fastio_in[1] ),
    .med_enable(\fastio_med_enable[1] ),
    .oe_l(\fastio_oe_l[1] ),
    .out_l(\fastio_out_l[1] ),
    .pad(gpio_noesd[1]),
    .strong_enable(\fastio_strong_enable[1] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio10 (
    .in(\fastio_in[10] ),
    .med_enable(\fastio_med_enable[10] ),
    .oe_l(\fastio_oe_l[10] ),
    .out_l(\fastio_out_l[10] ),
    .pad(io_analog[3]),
    .strong_enable(\fastio_strong_enable[10] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio11 (
    .in(\fastio_in[11] ),
    .med_enable(\fastio_med_enable[11] ),
    .oe_l(\fastio_oe_l[11] ),
    .out_l(\fastio_out_l[11] ),
    .pad(io_analog[4]),
    .strong_enable(\fastio_strong_enable[11] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio12 (
    .in(\fastio_in[12] ),
    .med_enable(\fastio_med_enable[12] ),
    .oe_l(\fastio_oe_l[12] ),
    .out_l(\fastio_out_l[12] ),
    .pad(io_analog[5]),
    .strong_enable(\fastio_strong_enable[12] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio13 (
    .in(\fastio_in[13] ),
    .med_enable(\fastio_med_enable[13] ),
    .oe_l(\fastio_oe_l[13] ),
    .out_l(\fastio_out_l[13] ),
    .pad(io_analog[6]),
    .strong_enable(\fastio_strong_enable[13] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio14 (
    .in(\fastio_in[14] ),
    .med_enable(\fastio_med_enable[14] ),
    .oe_l(\fastio_oe_l[14] ),
    .out_l(\fastio_out_l[14] ),
    .pad(io_analog[7]),
    .strong_enable(\fastio_strong_enable[14] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio15 (
    .in(\fastio_in[15] ),
    .med_enable(\fastio_med_enable[15] ),
    .oe_l(\fastio_oe_l[15] ),
    .out_l(\fastio_out_l[15] ),
    .pad(io_analog[8]),
    .strong_enable(\fastio_strong_enable[15] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio16 (
    .in(\fastio_in[16] ),
    .med_enable(\fastio_med_enable[16] ),
    .oe_l(\fastio_oe_l[16] ),
    .out_l(\fastio_out_l[16] ),
    .pad(io_analog[9]),
    .strong_enable(\fastio_strong_enable[16] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio17 (
    .in(\fastio_in[17] ),
    .med_enable(\fastio_med_enable[17] ),
    .oe_l(\fastio_oe_l[17] ),
    .out_l(\fastio_out_l[17] ),
    .pad(io_analog[10]),
    .strong_enable(\fastio_strong_enable[17] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio18 (
    .in(\fastio_in[18] ),
    .med_enable(\fastio_med_enable[18] ),
    .oe_l(\fastio_oe_l[18] ),
    .out_l(\fastio_out_l[18] ),
    .pad(gpio_noesd[7]),
    .strong_enable(\fastio_strong_enable[18] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio19 (
    .in(\fastio_in[19] ),
    .med_enable(\fastio_med_enable[19] ),
    .oe_l(\fastio_oe_l[19] ),
    .out_l(\fastio_out_l[19] ),
    .pad(gpio_noesd[8]),
    .strong_enable(\fastio_strong_enable[19] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio2 (
    .in(\fastio_in[2] ),
    .med_enable(\fastio_med_enable[2] ),
    .oe_l(\fastio_oe_l[2] ),
    .out_l(\fastio_out_l[2] ),
    .pad(gpio_noesd[2]),
    .strong_enable(\fastio_strong_enable[2] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio20 (
    .in(\fastio_in[20] ),
    .med_enable(\fastio_med_enable[20] ),
    .oe_l(\fastio_oe_l[20] ),
    .out_l(\fastio_out_l[20] ),
    .pad(gpio_noesd[9]),
    .strong_enable(\fastio_strong_enable[20] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio21 (
    .in(\fastio_in[21] ),
    .med_enable(\fastio_med_enable[21] ),
    .oe_l(\fastio_oe_l[21] ),
    .out_l(\fastio_out_l[21] ),
    .pad(gpio_noesd[10]),
    .strong_enable(\fastio_strong_enable[21] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio22 (
    .in(\fastio_in[22] ),
    .med_enable(\fastio_med_enable[22] ),
    .oe_l(\fastio_oe_l[22] ),
    .out_l(\fastio_out_l[22] ),
    .pad(gpio_noesd[11]),
    .strong_enable(\fastio_strong_enable[22] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio23 (
    .in(\fastio_in[23] ),
    .med_enable(\fastio_med_enable[23] ),
    .oe_l(\fastio_oe_l[23] ),
    .out_l(\fastio_out_l[23] ),
    .pad(gpio_noesd[12]),
    .strong_enable(\fastio_strong_enable[23] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio24 (
    .in(\fastio_in[24] ),
    .med_enable(\fastio_med_enable[24] ),
    .oe_l(\fastio_oe_l[24] ),
    .out_l(\fastio_out_l[24] ),
    .pad(gpio_noesd[13]),
    .strong_enable(\fastio_strong_enable[24] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio25 (
    .in(\fastio_in[25] ),
    .med_enable(\fastio_med_enable[25] ),
    .oe_l(\fastio_oe_l[25] ),
    .out_l(\fastio_out_l[25] ),
    .pad(gpio_noesd[14]),
    .strong_enable(\fastio_strong_enable[25] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio26 (
    .in(\fastio_in[26] ),
    .med_enable(\fastio_med_enable[26] ),
    .oe_l(\fastio_oe_l[26] ),
    .out_l(\fastio_out_l[26] ),
    .pad(gpio_noesd[15]),
    .strong_enable(\fastio_strong_enable[26] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio27 (
    .in(\fastio_in[27] ),
    .med_enable(\fastio_med_enable[27] ),
    .oe_l(\fastio_oe_l[27] ),
    .out_l(\fastio_out_l[27] ),
    .pad(gpio_noesd[16]),
    .strong_enable(\fastio_strong_enable[27] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio3 (
    .in(\fastio_in[3] ),
    .med_enable(\fastio_med_enable[3] ),
    .oe_l(\fastio_oe_l[3] ),
    .out_l(\fastio_out_l[3] ),
    .pad(gpio_noesd[3]),
    .strong_enable(\fastio_strong_enable[3] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio4 (
    .in(\fastio_in[4] ),
    .med_enable(\fastio_med_enable[4] ),
    .oe_l(\fastio_oe_l[4] ),
    .out_l(\fastio_out_l[4] ),
    .pad(gpio_noesd[4]),
    .strong_enable(\fastio_strong_enable[4] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio5 (
    .in(\fastio_in[5] ),
    .med_enable(\fastio_med_enable[5] ),
    .oe_l(\fastio_oe_l[5] ),
    .out_l(\fastio_out_l[5] ),
    .pad(gpio_noesd[5]),
    .strong_enable(\fastio_strong_enable[5] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio6 (
    .in(\fastio_in[6] ),
    .med_enable(\fastio_med_enable[6] ),
    .oe_l(\fastio_oe_l[6] ),
    .out_l(\fastio_out_l[6] ),
    .pad(gpio_noesd[6]),
    .strong_enable(\fastio_strong_enable[6] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio7 (
    .in(\fastio_in[7] ),
    .med_enable(\fastio_med_enable[7] ),
    .oe_l(\fastio_oe_l[7] ),
    .out_l(\fastio_out_l[7] ),
    .pad(io_analog[0]),
    .strong_enable(\fastio_strong_enable[7] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio8 (
    .in(\fastio_in[8] ),
    .med_enable(\fastio_med_enable[8] ),
    .oe_l(\fastio_oe_l[8] ),
    .out_l(\fastio_out_l[8] ),
    .pad(io_analog[1]),
    .strong_enable(\fastio_strong_enable[8] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  armleo_gpio fastio9 (
    .in(\fastio_in[9] ),
    .med_enable(\fastio_med_enable[9] ),
    .oe_l(\fastio_oe_l[9] ),
    .out_l(\fastio_out_l[9] ),
    .pad(io_analog[2]),
    .strong_enable(\fastio_strong_enable[9] ),
    .vdd(vccd2),
    .vddio(vdda2),
    .vss(vssd2),
    .vssio(vssa2)
  );
  carrack_wrapper wrp (
    .fastio_in({ \fastio_in[27] , \fastio_in[26] , \fastio_in[25] , \fastio_in[24] , \fastio_in[23] , \fastio_in[22] , \fastio_in[21] , \fastio_in[20] , \fastio_in[19] , \fastio_in[18] , \fastio_in[17] , \fastio_in[16] , \fastio_in[15] , \fastio_in[14] , \fastio_in[13] , \fastio_in[12] , \fastio_in[11] , \fastio_in[10] , \fastio_in[9] , \fastio_in[8] , \fastio_in[7] , \fastio_in[6] , \fastio_in[5] , \fastio_in[4] , \fastio_in[3] , \fastio_in[2] , \fastio_in[1] , \fastio_in[0]  }),
    .fastio_med_enable({ \fastio_med_enable[27] , \fastio_med_enable[26] , \fastio_med_enable[25] , \fastio_med_enable[24] , \fastio_med_enable[23] , \fastio_med_enable[22] , \fastio_med_enable[21] , \fastio_med_enable[20] , \fastio_med_enable[19] , \fastio_med_enable[18] , \fastio_med_enable[17] , \fastio_med_enable[16] , \fastio_med_enable[15] , \fastio_med_enable[14] , \fastio_med_enable[13] , \fastio_med_enable[12] , \fastio_med_enable[11] , \fastio_med_enable[10] , \fastio_med_enable[9] , \fastio_med_enable[8] , \fastio_med_enable[7] , \fastio_med_enable[6] , \fastio_med_enable[5] , \fastio_med_enable[4] , \fastio_med_enable[3] , \fastio_med_enable[2] , \fastio_med_enable[1] , \fastio_med_enable[0]  }),
    .fastio_oe_l({ \fastio_oe_l[27] , \fastio_oe_l[26] , \fastio_oe_l[25] , \fastio_oe_l[24] , \fastio_oe_l[23] , \fastio_oe_l[22] , \fastio_oe_l[21] , \fastio_oe_l[20] , \fastio_oe_l[19] , \fastio_oe_l[18] , \fastio_oe_l[17] , \fastio_oe_l[16] , \fastio_oe_l[15] , \fastio_oe_l[14] , \fastio_oe_l[13] , \fastio_oe_l[12] , \fastio_oe_l[11] , \fastio_oe_l[10] , \fastio_oe_l[9] , \fastio_oe_l[8] , \fastio_oe_l[7] , \fastio_oe_l[6] , \fastio_oe_l[5] , \fastio_oe_l[4] , \fastio_oe_l[3] , \fastio_oe_l[2] , \fastio_oe_l[1] , \fastio_oe_l[0]  }),
    .fastio_out_l({ \fastio_out_l[27] , \fastio_out_l[26] , \fastio_out_l[25] , \fastio_out_l[24] , \fastio_out_l[23] , \fastio_out_l[22] , \fastio_out_l[21] , \fastio_out_l[20] , \fastio_out_l[19] , \fastio_out_l[18] , \fastio_out_l[17] , \fastio_out_l[16] , \fastio_out_l[15] , \fastio_out_l[14] , \fastio_out_l[13] , \fastio_out_l[12] , \fastio_out_l[11] , \fastio_out_l[10] , \fastio_out_l[9] , \fastio_out_l[8] , \fastio_out_l[7] , \fastio_out_l[6] , \fastio_out_l[5] , \fastio_out_l[4] , \fastio_out_l[3] , \fastio_out_l[2] , \fastio_out_l[1] , \fastio_out_l[0]  }),
    .fastio_strong_enable({ \fastio_strong_enable[27] , \fastio_strong_enable[26] , \fastio_strong_enable[25] , \fastio_strong_enable[24] , \fastio_strong_enable[23] , \fastio_strong_enable[22] , \fastio_strong_enable[21] , \fastio_strong_enable[20] , \fastio_strong_enable[19] , \fastio_strong_enable[18] , \fastio_strong_enable[17] , \fastio_strong_enable[16] , \fastio_strong_enable[15] , \fastio_strong_enable[14] , \fastio_strong_enable[13] , \fastio_strong_enable[12] , \fastio_strong_enable[11] , \fastio_strong_enable[10] , \fastio_strong_enable[9] , \fastio_strong_enable[8] , \fastio_strong_enable[7] , \fastio_strong_enable[6] , \fastio_strong_enable[5] , \fastio_strong_enable[4] , \fastio_strong_enable[3] , \fastio_strong_enable[2] , \fastio_strong_enable[1] , \fastio_strong_enable[0]  }),
    .io_in(io_in),
    .io_oeb(io_oeb),
    .io_out(io_out),
    .user_clock2(user_clock2),
    .user_irq(user_irq),
    .vccd1(vccd1),
    .vssd1(vssd1),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wbs_ack_o(wbs_ack_o),
    .wbs_adr_i(wbs_adr_i),
    .wbs_cyc_i(wbs_cyc_i),
    .wbs_dat_i(wbs_dat_i),
    .wbs_dat_o(wbs_dat_o),
    .wbs_sel_i(wbs_sel_i),
    .wbs_stb_i(wbs_stb_i),
    .wbs_we_i(wbs_we_i)
  );
endmodule
